/**
 * Dashboard & Weather Translation Helper for WeatherGPT.
 * Localizes weather conditions, insight headlines, advisory cards, time strings,
 * and UI labels into all supported Indian languages (Marathi, Hindi, Tamil, Telugu, etc.).
 */

import { LanguageCode } from '../context/LanguageContext';

export interface WeatherConditionTranslations {
  [englishTerm: string]: { [lang in LanguageCode]?: string };
}

export const WEATHER_CONDITIONS_MAP: Record<string, Record<LanguageCode, string>> = {
  'clear sky': {
    en: 'Clear Sky',
    hi: 'साफ आसमान',
    mr: 'निरभ्र आकाश',
    ta: 'தெளிவான வானம்',
    te: 'నిర్మలమైన ఆకాశం',
    kn: 'ಸ್ವಚ್ಛ ಆಕಾಶ',
    ml: 'തെളിഞ്ഞ ആകാശം',
    bn: 'পরিষ্কার আকাশ',
    gu: 'સ્વચ્છ આકાશ',
    pa: 'ਸਾਫ਼ ਅਸਮਾਨ',
    or: 'ନିର୍ମଳ ଆକାଶ',
  },
  'mainly clear': {
    en: 'Mainly Clear',
    hi: 'मुख्यतः साफ',
    mr: 'मुख्यतः निरभ्र',
    ta: 'பெரும்பாலும் தெளிவானது',
    te: 'ఎక్కువగా నిర్మలంగా ఉంది',
    kn: 'ಹೆಚ್ಚಾಗಿ ಸ್ವಚ್ಛ',
    ml: 'പ്രധാനമായും തെളിഞ്ഞത്',
    bn: 'বেশিরভাগ পরিষ্কার',
    gu: 'મુખ્યત્વે સ્વચ્છ',
    pa: 'ਮੁੱਖ ਤੌਰ ਤੇ ਸਾਫ਼',
    or: 'ମୁଖ୍ୟତଃ ନିର୍ମଳ',
  },
  'partly cloudy': {
    en: 'Partly Cloudy',
    hi: 'आंशिक रूप से बादल',
    mr: 'अंशतः ढगाळ',
    ta: 'பகுதி மேகமூட்டம்',
    te: 'పాక్షికంగా మేఘావృతం',
    kn: 'ಭಾಗಶಃ ಮೋಡ ಕವಿದ',
    ml: 'ഭാഗികമായി മേഘാവൃതം',
    bn: 'আংশিক মেঘলা',
    gu: 'અંશતઃ વાદળછાયું',
    pa: 'ਅੰਸ਼ਕ ਤੌਰ ਤੇ ਬੱਦਲਵਾਈ',
    or: 'ଆଂଶିକ ମେଘୁଆ',
  },
  'overcast': {
    en: 'Overcast',
    hi: 'घने बादल',
    mr: 'ढगाळ हवामान',
    ta: 'மேகமூட்டம்',
    te: 'పూర్తిగా మేఘావృతం',
    kn: 'ಮೋಡ ಕವಿದ ವಾತಾವರಣ',
    ml: 'പൂർണ്ണമായും മേഘാവൃതം',
    bn: 'মেঘলা আকাশ',
    gu: 'વાદળછાયું વાતાવરણ',
    pa: 'ਪੂਰੀ ਤਰ੍ਹਾਂ ਬੱਦਲਵਾਈ',
    or: 'ସମ୍ପୂର୍ଣ୍ଣ ମେଘୁଆ',
  },
  'light drizzle': {
    en: 'Light Drizzle',
    hi: 'हल्की बूंदाबांदी',
    mr: 'हलकी रिमझिम',
    ta: 'லேசான தூறல்',
    te: 'తేలికపాటి జల్లులు',
    kn: 'ಲಘು ತುಂತುರು ಮಳೆ',
    ml: 'നേരിയ ചാറ്റൽമഴ',
    bn: 'হালকা গুঁড়ি গুঁড়ি বৃষ্টি',
    gu: 'હળવી ઝરમર',
    pa: 'ਹਲਕੀ ਬੂੰਦਾ-ਬਾਂਦੀ',
    or: 'ହାଲୁକା ଝିପିଝିପି ବର୍ଷା',
  },
  'drizzle': {
    en: 'Drizzle',
    hi: 'बूंदाबांदी',
    mr: 'रिमझिम पाऊस',
    ta: 'தூறல்',
    te: 'జల్లులు',
    kn: 'ತುಂತುರು ಮಳೆ',
    ml: 'ചാറ്റൽമഴ',
    bn: 'গুঁড়ি গুঁড়ি বৃষ্টি',
    gu: 'ઝરમર વરસાદ',
    pa: 'ਬੂੰਦਾ-ਬਾਂਦੀ',
    or: 'ଝିପିଝିପି ବର୍ଷା',
  },
  'rain': {
    en: 'Rain',
    hi: 'बारिश',
    mr: 'पाऊस',
    ta: 'மழை',
    te: 'వర్షం',
    kn: 'ಮಳೆ',
    ml: 'മഴ',
    bn: 'বৃষ্টি',
    gu: 'વરસાદ',
    pa: 'ਮੀਂਹ',
    or: 'ବର୍ଷା',
  },
  'heavy rain': {
    en: 'Heavy Rain',
    hi: 'भारी बारिश',
    mr: 'मुसळधार पाऊस',
    ta: 'கனமழை',
    te: 'భారీ వర్షం',
    kn: 'ಭಾರಿ ಮಳೆ',
    ml: 'കനത്ത മഴ',
    bn: 'ভারী বৃষ্টি',
    gu: 'ભારે વરસાદ',
    pa: 'ਭਾਰੀ ਮੀਂਹ',
    or: 'ପ୍ରବଳ ବର୍ଷା',
  },
  'thunderstorm': {
    en: 'Thunderstorm',
    hi: 'गरज के साथ बारिश',
    mr: 'वादळी पाऊस',
    ta: 'இடியுடன் கூடிய மழை',
    te: 'ఉరుములతో కూడిన వర్షం',
    kn: 'ಗುಡುಗು ಸಹಿತ ಮಳೆ',
    ml: 'ഇടിമിന്നലോടുകൂടിയ മഴ',
    bn: 'বজ্রবিদ্যুৎ সহ বৃষ্টি',
    gu: 'ગાજવીજ સાથે વરસાદ',
    pa: 'ਗਰਜ ਨਾਲ ਮੀਂਹ',
    or: 'ଘଡ଼ଘଡ଼ି ସହ ବର୍ଷା',
  },
  'fog': {
    en: 'Fog',
    hi: 'कोहरा',
    mr: 'धुके',
    ta: 'மூடுபனி',
    te: 'పొగమంచు',
    kn: 'ದಟ್ಟ ಮಂಜು',
    ml: 'മഞ്ഞുമൂടിയ',
    bn: 'কুয়াশা',
    gu: 'ધુમ્મસ',
    pa: 'ਧੁੰਦ',
    or: 'କୁହୁଡ଼ି',
  },
};

export const UI_PHRASES: Record<string, Record<LanguageCode, string>> = {
  heroSubtitle: {
    en: 'Your exact location, translated into a weather decision.',
    hi: 'आपका सटीक स्थान, मौसम निर्णय में परिवर्तित।',
    mr: 'तुमचे अचूक स्थान, हवामान निर्णयात रूपांतरित.',
    ta: 'உங்கள் துல்லியமான இடம், வானிலை முடிவாக மாற்றப்பட்டது.',
    te: 'మీ ఖచ్చితమైన ప్రదేశం, వాతావరణ నిర్ణయంగా మార్చబడింది.',
    kn: 'ನಿಮ್ಮ ನಿಖರ ಸ್ಥಳ, ಹವಾಮಾನ ನಿರ್ಧಾರವಾಗಿ ಪರಿವರ್ತಿಸಲಾಗಿದೆ.',
    ml: 'നിങ്ങളുടെ കൃത്യമായ ലൊക്കേഷൻ, കാലാവസ്ഥ തീരുമാനമാക്കി മാറ്റി.',
    bn: 'আপনার সঠিক অবস্থান, আবহাওয়ার সিদ্ধান্তে রূপান্তরিত।',
    gu: 'તમારું ચોક્કસ સ્થાન, હવામાન નિર્ણયમાં રૂપાંતરિત.',
    pa: 'ਤੁਹਾਡਾ ਸਹੀ ਸਥਾਨ, ਮੌਸਮ ਦੇ ਫੈਸਲੇ ਵਿੱਚ ਬਦਲਿਆ ਗਿਆ।',
    or: 'ଆପଣଙ୍କ ସଠିକ୍ ସ୍ଥାନ, ପାଣିପାଗ ନିଷ୍ପତ୍ତିରେ ରୂପାନ୍ତରିତ।',
  },
  liveAtmosphericSync: {
    en: 'Live Atmospheric Sync',
    hi: 'लाइव वायुमंडलीय सिंक',
    mr: 'थेट वातावरणीय समन्वय',
    ta: 'நேரடி வளிமண்டல ஒத்திசைவு',
    te: 'ప్రత్యక్ష వాతావరణ సమకాలీకరణ',
    kn: 'ನೇರ ವಾತಾವರಣ ಸಮನ್ವಯ',
    ml: 'തത്സമയ അന്തരീക്ഷ സമന്വയം',
    bn: 'লাইভ বায়ুমণ্ডলীয় সমন্বয়',
    gu: 'લાઇવ વાતાવરણીય સમન્વય',
    pa: 'ਲਾਈਵ ਵਾਯੂਮੰਡਲ ਸਿੰਕ',
    or: 'ପ୍ରତ୍ୟକ୍ଷ ବାୟୁମଣ୍ଡଳୀୟ ସମନ୍ୱୟ',
  },
  feelsLike: {
    en: 'Feels like',
    hi: 'महसूस हो रहा है',
    mr: 'जाणवणारे तापमान',
    ta: 'உணர்வது',
    te: 'అనిపించే ఉష్ణోగ్రత',
    kn: 'ಅನಿಸುವ ತಾಪಮಾನ',
    ml: 'തോന്നുന്ന താപനില',
    bn: 'অনুভূত তাপমাত্রা',
    gu: 'અનુભવાતું તાપમાન',
    pa: 'ਮਹਿਸੂਸ ਹੁੰਦਾ ਹੈ',
    or: 'ଅନୁଭୂତ ତାପମାତ୍ରା',
  },
  updatedJustNow: {
    en: 'Updated Just now',
    hi: 'अभी अपडेट किया गया',
    mr: 'आत्ताच अद्यतनित',
    ta: 'இப்போது புதுப்பிக்கப்பட்டது',
    te: 'ఇప్పుడే నవీకరించబడింది',
    kn: 'ಈಗಷ್ಟೇ ನವೀಕರಿಸಲಾಗಿದೆ',
    ml: 'ഇപ്പോൾ അപ്ഡേറ്റ് ചെയ്തു',
    bn: 'এইমাত্র আপডেট করা হয়েছে',
    gu: 'હમણાં જ અપડેટ કર્યું',
    pa: 'ਹੁਣੇ ਅਪਡੇਟ ਕੀਤਾ ਗਿਆ',
    or: 'ଏବେ ଅପଡେଟ୍ ହୋଇଛି',
  },
  liveLocation: {
    en: 'Live location',
    hi: 'लाइव स्थान',
    mr: 'थेट स्थान',
    ta: 'நேரடி இருப்பிடம்',
    te: 'ప్రత్యక్ష ప్రదేశం',
    kn: 'ನೇರ ಸ್ಥಳ',
    ml: 'തത്സമയ ലൊക്കേഷൻ',
    bn: 'লাইভ অবস্থান',
    gu: 'લાઇવ સ્થાન',
    pa: 'ਲਾਈਵ ਸਥਾਨ',
    or: 'ପ୍ରତ୍ୟକ୍ଷ ସ୍ଥାନ',
  },
  selectedLocation: {
    en: 'Selected location',
    hi: 'चयनित स्थान',
    mr: 'निवडलेले स्थान',
    ta: 'தேர்ந்தெடுக்கப்பட்ட இடம்',
    te: 'ఎంచుకున్న ప్రదేశం',
    kn: 'ಆಯ್ಕೆಮಾಡಿದ ಸ್ಥಳ',
    ml: 'തിരഞ്ഞെടുത്ത ലൊക്കേഷൻ',
    bn: 'নির্বাচিত অবস্থান',
    gu: 'પસંદ કરેલ સ્થાન',
    pa: 'ਚੁਣਿਆ ਗਿਆ ਸਥਾਨ',
    or: 'ଚୟନିତ ସ୍ଥାନ',
  },
  askAi: {
    en: 'Ask AI',
    hi: 'AI से पूछें',
    mr: 'AI ला विचारा',
    ta: 'AI யிடம் கேளுங்கள்',
    te: 'AI ని అడగండి',
    kn: 'AI ಯನ್ನು ಕೇಳಿ',
    ml: 'AI യോട് ചോദിക്കൂ',
    bn: 'AI কে জিজ্ঞাসা করুন',
    gu: 'AI ને પૂછો',
    pa: 'AI ਨੂੰ ਪੁੱਛੋ',
    or: 'AI କୁ ପଚାରନ୍ତୁ',
  },
  carryUmbrella: {
    en: 'Carry an umbrella',
    hi: 'छाता साथ रखें',
    mr: 'छत्री सोबत ठेवा',
    ta: 'குடை எடுத்துச் செல்லுங்கள்',
    te: 'గొడుగు వెంట ఉంచుకోండి',
    kn: 'ಕೊಡೆ ತೆಗೆದುಕೊಂಡು ಹೋಗಿ',
    ml: 'കുട കരുതുക',
    bn: 'সঙ্গে ছাতা রাখুন',
    gu: 'સાથે છત્રી રાખો',
    pa: 'ਛੱਤਰੀ ਨਾਲ ਰੱਖੋ',
    or: 'ଛତା ସାଥିରେ ରଖନ୍ତୁ',
  },
  rainProbabilityIncrease: {
    en: 'Rain probability increases after afternoon in your area.',
    hi: 'आपके क्षेत्र में दोपहर के बाद बारिश की संभावना बढ़ जाएगी।',
    mr: 'तुमच्या भागात दुपारनंतर पावसाची शक्यता जास्त आहे.',
    ta: 'உங்கள் பகுதியில் மதியத்திற்குப் பிறகு மழை பெய்ய வாய்ப்புள்ளது.',
    te: 'మీ ప్రాంతంలో మధ్యాహ్నం తర్వాత వర్షం పడే అవకాశం ఉంది.',
    kn: 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಮಧ್ಯಾಹ್ನದ ನಂತರ ಮಳೆಯಾಗುವ ಸಾಧ್ಯತೆಯಿದೆ.',
    ml: 'നിങ്ങളുടെ പ്രദേശത്ത് ഉച്ചയ്ക്ക് ശേഷം മഴയ്ക്ക് സാധ്യതയുണ്ട്.',
    bn: 'আপনার এলাকায় দুপুরের পর বৃষ্টির সম্ভাবনা বেশি।',
    gu: 'તમારા વિસ્તારમાં બપોર પછી વરસાદની શક્યતા વધારે છે.',
    pa: 'ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਦੁਪਹਿਰ ਤੋਂ ਬਾਅਦ ਮੀਂਹ ਪੈਣ ਦੀ ਸੰਭਾਵਨਾ ਹੈ।',
    or: 'ଆପଣଙ୍କ ଅଞ୍ଚଳରେ ଅପରାହ୍ନ ପରେ ବର୍ଷା ହେବାର ସମ୍ଭାବନା ଅଛି।',
  },
  intelligenceInsightsTitle: {
    en: 'WeatherGPT Intelligence Insights',
    hi: 'WeatherGPT मौसम अंतर्दृष्टि',
    mr: 'WeatherGPT बुद्धिमत्ता अंतर्दृष्टी',
    ta: 'WeatherGPT நுண்ணறிவு பார்வைகள்',
    te: 'WeatherGPT వాతావరణ విశ్లేషణ',
    kn: 'WeatherGPT ಹವಾಮಾನ ಒಳನೋಟಗಳು',
    ml: 'WeatherGPT കാലാവസ്ഥ നിരീക്ഷണങ്ങൾ',
    bn: 'WeatherGPT আবহাওয়া অন্তর্দৃষ্টি',
    gu: 'WeatherGPT હવામાન આંતરદ્રષ્ટિ',
    pa: 'WeatherGPT ਮੌਸਮ ਸੰਬੰਧੀ ਜਾਣਕਾਰੀ',
    or: 'WeatherGPT ପାଣିପାଗ ବିଶ୍ଳେଷଣ',
  },
  rainExpectedToday: {
    en: 'Rain Expected Today',
    hi: 'आज बारिश की संभावना',
    mr: 'आज पाऊस पडण्याची शक्यता',
    ta: 'இன்று மழை எதிர்பார்க்கப்படுகிறது',
    te: 'ఈరోజు వర్షం పడే అవకాశం ఉంది',
    kn: 'ಇಂದು ಮಳೆಯಾಗುವ ನಿರೀಕ್ಷೆಯಿದೆ',
    ml: 'ഇന്ന് മഴ പ്രതീക്ഷിക്കുന്നു',
    bn: 'আজ বৃষ্টির সম্ভাবনা রয়েছে',
    gu: 'આજે વરસાદની અપેક્ષા છે',
    pa: 'ਅੱਜ ਮੀਂਹ ਪੈਣ ਦੀ ਉਮੀਦ ਹੈ',
    or: 'ଆଜି ବର୍ଷା ହେବାର ସମ୍ଭାବନା ଅଛି',
  },
  pleasantTemperature: {
    en: 'Pleasant Temperature Profile',
    hi: 'सुखद तापमान प्रोफ़ाइल',
    mr: 'आल्हाददायक तापमान प्रोफाइल',
    ta: 'இதமான வெப்பநிலை',
    te: 'ఆహ్లాదకరమైన ఉష్ణోగ్రత',
    kn: 'ಆಹ್ಲಾದಕರ ತಾಪಮಾನ',
    ml: 'സുഖകരമായ താപനില',
    bn: 'মনোরম তাপমাত্রা',
    gu: 'આહલાદક તાપમાન',
    pa: 'ਸੁਹਾਵਣਾ ਤਾਪਮਾਨ',
    or: 'ଆରାମଦାୟକ ତାପମାତ୍ରା',
  },
  advisory: {
    en: 'ADVISORY',
    hi: 'परामर्श',
    mr: 'सल्ला',
    ta: 'ஆலோசனை',
    te: 'సలహా',
    kn: 'ಸಲಹೆ',
    ml: 'നിർദ്ദേശം',
    bn: 'পরামর্শ',
    gu: 'સલાહ',
    pa: 'ਸਲਾਹ',
    or: 'ପରାମର୍ଶ',
  },
  weather: {
    en: 'Weather',
    hi: 'मौसम',
    mr: 'हवामान',
    ta: 'வானிலை',
    te: 'వాతావరణం',
    kn: 'ಹವಾಮಾನ',
    ml: 'കാലാവസ്ഥ',
    bn: 'আবহাওয়া',
    gu: 'હવામાન',
    pa: 'ਮੌਸਮ',
    or: 'ପାଣିପାଗ',
  },
  airQuality: {
    en: 'Air Quality',
    hi: 'हवा की गुणवत्ता',
    mr: 'हवेची गुणवत्ता',
    ta: 'காற்று தரம்',
    te: 'గాలి నాణ్యత',
    kn: 'ವಾಯು ಗುಣಮಟ್ಟ',
    ml: 'വായു ഗുണനിലവാരം',
    bn: 'বায়ুর মান',
    gu: 'હવાની ગુણવત્તા',
    pa: 'ਹਵਾ ਦੀ ਗੁਣਵੱਤਾ',
    or: 'ବାୟୁ ଗୁଣବତ୍ତା',
  },
  alerts: {
    en: 'Alerts',
    hi: 'चेतावनी',
    mr: 'इशारे',
    ta: 'எச்சரிக்கைகள்',
    te: 'హెచ్చరికలు',
    kn: 'ಎಚ್ಚರಿಕೆಗಳು',
    ml: 'മുന്നറിയിപ്പുകൾ',
    bn: 'সতর্কতা',
    gu: 'ચેતવણીઓ',
    pa: 'ਚੇਤਾਵਨੀਆਂ',
    or: 'ସତର୍କତା',
  },
  mapRadar: {
    en: 'Map Radar',
    hi: 'मानचित्र व रडार',
    mr: 'नकाशा व रडार',
    ta: 'வரைபடம் ரேடார்',
    te: 'మ్యాప్ రాడార్',
    kn: 'ನಕ್ಷೆ ರೇಡಾರ್',
    ml: 'മാപ്പ് റഡാർ',
    bn: 'ম্যাপ রাডার',
    gu: 'નકશો અને રડાર',
    pa: 'ਨਕਸ਼ਾ ਰਡਾਰ',
    or: 'ମାନଚିତ୍ର ରାଡାର',
  },
  citizenRole: {
    en: 'CITIZEN',
    hi: 'नागरिक',
    mr: 'नागरिक',
    ta: 'குடிமகன்',
    te: 'పౌరుడు',
    kn: 'ನಾಗರಿಕ',
    ml: 'പൗരൻ',
    bn: 'নাগরিক',
    gu: 'નાગરિક',
    pa: 'ਨਾਗਰਿਕ',
    or: 'ନାଗରିକ',
  },
};

/**
 * Translate weather condition string (e.g. "Light Drizzle", "Rain", "Clear Sky")
 */
export function translateCondition(condition: string, lang: LanguageCode): string {
  if (!condition || lang === 'en') return condition || 'Clear Sky';
  const key = condition.toLowerCase().trim();
  if (WEATHER_CONDITIONS_MAP[key] && WEATHER_CONDITIONS_MAP[key][lang]) {
    return WEATHER_CONDITIONS_MAP[key][lang]!;
  }
  // Partial substring matching
  for (const [condKey, langMap] of Object.entries(WEATHER_CONDITIONS_MAP)) {
    if (key.includes(condKey) && langMap[lang]) {
      return langMap[lang]!;
    }
  }
  return condition;
}

/**
 * Translate UI phrase by key
 */
export function translatePhrase(key: string, lang: LanguageCode): string {
  if (UI_PHRASES[key] && UI_PHRASES[key][lang]) {
    return UI_PHRASES[key][lang];
  }
  return UI_PHRASES[key]?.en || key;
}
